### ISSUE TITLE
outdated BackendUrl in hosted utils.js

### ISSUE THREAD

**Issue by simonstey** [petrbroz/forgist#1]
the utils.js version hosted at https://forgist.autodesk.io/client/utils.js uses an outdated BackendUrl:
```js
const forgist = {
    BackendUrl: 'https://forgist.herokuapp.com'
};
``` 
as a result codepen examples/template don't work.. 
please update the hosted version with -> 
https://github.com/petrbroz/forgist/blob/b8bcc4cc15b238bfa809f306e2fdc2a80de9f2bc/client/utils.js#L1-L3

**Comment by petrbroz** [comment]
Thank you for the heads up! The hosted version is now updated.
